spring.application.name=gestao-corrida
spring.datasource.url=jdbc:postgresql://localhost:5433/autodromo_db
spring.datasource.username=admin
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true